### ISSUE TITLE
`blinks` directory/.csv not present

### ISSUE THREAD

**Issue by da-gazzi** [aangelopoulos/event_based_gaze_tracking#1]
Dear authors
We would like to use your dataset. In the top-level README, a `blinks` directory and corresponding `.csv` file(s) (presumably listing frames during which the user blinks) are mentioned - unfortunately, I cannot find these files in either the downloaded dataset or the repository. Could you make it available?

Thanks and best regards,
Georg Rutishauser

**Comment by aangelopoulos** [comment]
Looking into this, thank you for pointing it out.

**Comment by aangelopoulos** [comment]
Hi Georg,

  I looked through with my collaborators and we couldn't find this file -- and it's not in the gitignore, so I'm not sure it ever existed.  In other words, I think the error was in the README, as we may have had plans to implement blink detection but never did.

  To resolve, I removed the line about blinks in the README because it looks like we never implemented that feature. However, you can look at the paper to see how we do blink detection.  Basically, we fit an ellipse to the processed frame, and if it has sufficiently extreme eccentricity (ratio of major/minor axes), then we identify it as a blink.

  Hope that helps!  Sorry for the README error.

Best,
Anastasios
